Reorganize directory structure (#16)
Autotest
* Reorganize directory structure to add a new directory for "test" project
* Add a new module for tests (autotest)
* Add Java (tests) related entries to .gitignore
* feat: Add initial test structure
* feat: General clean up
- Clean up data directory structure
- Bump up Nex.js version to 15.2.3
- Simplify directory layout in tsconfig.json
* test: Initial commit for higher integration tests
* improve: Clean up test structure
* refactor: directory structure and introduce command handling mechanism
* feat: Add an explicit method to profile to figure out healthcheck endpoint.
* fix: Make CommandLauncher use a new feature in ProcessStreamer, where it can pass multiple arguments to a runner shell
* nit: Use "simpler style" more in Smoke
* feature: Improve Smoke (stability)
* refactor: Clean up Smoke structure
- Move to and create AppConductor and Browser under testbases package for clarity
* chore: Clean up project definition
- Move TestBase under tastbases package

Frontend

* refactor: Improve method names in Smoke and introduce a few placeholder methods.
* refactor: Introduce a TestBase, where methods shared across Tests are defined.
* feat: Add helper scripts placeholders
* feat: Add IDEA configuration file (simple-tt-frontend.iml)
* nit: Add nohup.out to .gitignore

Top:
* tool: Configure workspace
* refactor: Add .gitignore to autotest module
* chore: Remove processstreamer from project structure
- Remove process streamer from project structure as its GA version is now available.
- Bump up processstreamer version to 2.0.5
* chore: Define 'autotest' module
- Add 'autotest' as a subproject.
* chore: Add .env file to .gitignore
* chore: Bump up insdog-all version to 0.5.2
* chore: Remove related projects
- Remove related projects settings such as valid8j and insdog-all. from IDEA's configuration files.
Because simple-tt is now an independent one.
* chore: Remove external projects from IDEA settings

Tools
* tool: Add frontend controller
- Add frontend controller.
- Add its basic plugins.
* refactor: Make conductor tool independent of autotest as it can be used manually
* feat: Implement 'help' mode for conductor util
* feat: Introduce commandline options and help
- Introduce commandline options (--execute, --describe, and --help)
- Clean up stage name
- Introduce list-sgates
* feat: Make task definitions independent of the script as a config file
* fix: Correct handlings of arrays in JSON and in bash
* fix: Use /hello page instead of lsof -i to check service status
* fix: Use readlink -f to force absolute path for tools to register it in PATH.
* fix: Clean up messages
* fix: Make frontend log go to tools/var/log/frontend.log
* fix: Force newline at the end of the last line of cURL output in upload.rc
* fix: Add log directory resolver function to config.rc
* feat: Add debugging feature and make output colorized
* feature: Code clean up
* refactor: Rename CurlClient to CurlLauncher

diff --git a/tools/bin/conductor b/tools/bin/conductor
--- a/tools/bin/conductor
+++ b/tools/bin/conductor
@@ -6,6 +6,7 @@ shopt -s inherit_errexit nullglob
 source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/lib/utils.rc"
 source "$(dirname "$(dirname "${BASH_SOURCE[0]}")")/lib/config.rc"
 
+debug_enabled=false
 __execute_stage_driver_filename=
 __execute_stage_stage_name=
 function __perform_stage() {
@@ -24,22 +25,28 @@ function __perform_stage() {
       # shellcheck disable=SC2317
       echo "${__perform_stage_stage_name}"
     }
-    function help_stage() {
+    function describe_stage() {
       # shellcheck disable=SC2317
-      echo "no help available"
+      echo "no description available for this stage. (${*})"
     }
+    [[ -e "${__perform_stage_driver_filename}" ]] || abort "Neither a task nor a driver not found for : '${__perform_stage_stage_name}'"
     # shellcheck disable=SC1090
-    source "${__perform_stage_driver_filename}" || abort "Driver not found: '${__perform_stage_driver_filename}'"
+    source "${__perform_stage_driver_filename}" || abort "Failed to load driver: '${__perform_stage_driver_filename}'"
     if [[ "${_type}" == EXECUTE ]]; then
-      (message "EXECUTING:${_stage}:[${*}]" && execute_stage "$@" && message "DONE:${_stage}") || abort "FAILED:${_stage}"
-    elif [[ "${_type}" == HELP ]]; then
-      (echo "$(stage_name):: $(help_stage)") || abort "FAILED:${_stage}"
+      local _rest=("${@}") _debug=""
+      echo -e "\e[1;34mBEGIN STAGE:\e[0m \e[4m${_stage}\e[0m" >&2
+      if [[ "${debug_enabled}" == true ]]; then
+        _debug="x"
+      fi
+      (set -eu${_debug} -o pipefail -o errtrace; execute_stage "$@" | cat) || abort "\e[1;31mFAILED: \e[4m${_stage}\e[0m"
+      echo -e "\e[1;34mEND STAGE:\e[0m   \e[4m${_stage}\e[0m" >&2
+    elif [[ "${_type}" == DESCRIBE ]]; then
+      (echo "$(stage_name):: $(describe_stage "$@")") || abort "\e[1;31mFAILED: \e[4m${_stage}\e[0m"
     else
       abort "Unknown behavior type: '${_type}' was specified."
     fi
 
   } || {
-    message "FAILED:${_stage}"
     return 1
   }
   return 0
@@ -50,37 +57,79 @@ function perform() {
     return 0
   fi
   local _type="${1}"
-  local _first="${2}"
+  local _task="${2}"
   shift
   shift
-  if [[ "${_type}" != "EXECUTE" && "${_type}" != "HELP" ]]; then
+  if [[ "${_type}" != "EXECUTE" && "${_type}" != "DESCRIBE" ]]; then
     abort "Unknown behavior type: '${_type}'"
   fi
-  if [[ "${_first}" == STOP ]]; then
-    perform "${_type}" killall:node:npm "${@}"
-  elif [[ "${_first}" == START ]]; then
-    perform "${_type}" start:"$(resolve_frontend_basedir)" "${@}"
-  elif [[ "${_first}" == STATUS ]]; then
-    perform "${_type}" is_running "${@}"
-  elif [[ "${_first}" == REFRESH_EXECUTION_ENVIRONMENT ]]; then
-    perform "${_type}" refresh_execution_environment "${@}"
-  elif [[ "${_first}" == ERASE_DATASET ]]; then
-    perform "${_type}" wipe-datasets "${@}"
-  elif [[ "${_first}" == LOAD_DATASET ]]; then
-    perform "${_type}" upload:v2/run-1.json \
-            "${_type}" upload:v2/run-2.json "${@}"
+  if task_defined "${_task}"; then
+    local _task_defs _i
+    echo -e "\e[1;34mBEGIN TASK:\e[0m  \e[4m${_task}\e[0m" >&2
+    mapfile -t _task_defs < <(task_definition_for "${_task}")
+    for _i in "${_task_defs[@]}"; do
+      perform "${_type}" "${_i}" 2>&1
+    done < /dev/null 2>&1
+    if [[ "${#}" -gt 0 ]]; then
+      perform "${@}"
+    fi
+    echo -e "\e[1;34mEND TASK:\e[0m    \e[4m${_task}\e[0m" >&2
   else
-    IFS=':' read -r -a _args <<<"${_first}"
+    IFS=':' read -r -a _args <<<"${_task}"
     __perform_stage "${_type}" "${_args[@]}" || exit 1
     perform "${@}"
   fi
 }
 
-function main() {
-  if [[ "${#@}" == 0 ]]; then
-    perform EXECUTE STATUS
-  else
-    perform "${@}"
-  fi
+show_help() {
+  echo "Usage: $(basename "${0}") [--help] [--execute] task..."
+  echo
+  echo "Options:"
+  echo "  --help       Show this help message"
+  echo "  --execute    Run a given command (default)"
+  echo "  --describe   Describe a given command"
+  echo
+  echo "Try: $(basename "${0}") list-tasks and list-stages"
 }
+
+main() {
+  # Parse options
+  local _types=() _tasks=() _help=no
+  while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+      --help)
+        _help=yes
+        ;;
+      --describe)
+        _types+=("DESCRIBE")
+        ;;
+      --execute)
+        _types+=("EXECUTE")
+        ;;
+      --debug)
+        debug_enabled=true
+        ;;
+      -*)
+        echo "Unknown option: $1"
+        show_help
+        return 1
+        ;;
+      *)
+        _tasks+=("$1")
+        ;;
+    esac
+    shift
+  done
+  if [[ "${_help}" == yes || "${#_tasks[@]}" == 0 ]]; then
+    show_help
+    return 0
+  fi
+  if [[ "${#_types[@]}" == 0 ]]; then
+    _types=(EXECUTE)
+  fi
+  for _type in "${_types[@]}"; do
+    perform "${_type}" "${_tasks[@]}"
+  done
+}
+
 main "${@}"
